// react/src/components/Form.jsx
import React, {useState} from 'react'
import './form.scss'

export const Form = () => {

  const initState = {
    firstName: '',
    lastName: '',
    email: '',
    message: ''
  }

  const [formState, setFormState] = useState(initState)

  const handleOnChange = (e) => {
    setFormState({...formState, [e.target.name]: e.target.value})
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    alert(`Form submitted!! firstName: ${formState.firstName}, lastName: ${formState.lastName}, email: ${formState.email}, message: ${formState.message}`)
    setFormState(initState)
  }

  return (
    <div className="form__wrapper">

      <form className="form">
        <h1>Form</h1>
        <div className="form__section">
          <div className="form__field">
            <label className="form__label">First Name</label>
            <input
              className="form__input"
              id="firstName"
              name="firstName"
              type="text"
              value={formState.firstName}
              onChange={handleOnChange}
            />
          </div>
          <div className="form__field">
            <label className="form__label">Last Name</label>
            <input
              className="form__input"
              id="lastName"
              name="lastName"
              type="text"
              value={formState.lastName}
              onChange={handleOnChange}
            />
          </div>
        </div>

        <div className="form__section">
          <div className="form__field--fullWidth">
            <label className="form__label">Email</label>
            <input
              className="form__input"
              id="email"
              name="email"
              type="email"
              value={formState.email}
              onChange={handleOnChange}
            />
          </div>
        </div>

        <div className="form__section">
          <div className="form__field--fullWidth">
            <label className="form__label">Message</label>
            <textarea
              className="form__input form__textarea"
              id="message"
              name="message"
              value={formState.message}
              onChange={handleOnChange}
            />
          </div>
        </div>

        <button
          className='button button__ghost button--extraPadding'
          onClick={handleSubmit}
        >
          Send
        </button>
      </form>
    </div>
  )
}

// svelte/src/routes/form/index.svelte
<script>
  // import '../../styles/form.scss';

  let firstName = '';
  let lastName = '';
  let email = '';
  let message = '';

  const handleSubmit = (e) => {
    e.preventDefault()
    alert(`Form submitted!! firstName: ${firstName}, lastName: ${lastName}, email: ${email}, message: ${message}`)

    firstName = ''
    lastName = ''
    email = '';
    message = ''
  }

</script>

<svelte:head>
    <title>Form</title>
</svelte:head>

<div class="form__wrapper">

    <div class="form__preWrapper">
        <pre>First Name: {firstName}</pre>
        <pre>Last Name: {lastName}</pre>
        <pre>Email: {email}</pre>
        <pre>Message: {message}</pre>
    </div>

    <form class="form">
        <h1>Form</h1>
        <div class="form__section">
            <div class="form__field">
                <label class="form__label">First Name</label>
                <input class="form__input"
                       id="firstName"
                       name="firstName"
                       type="text"
                       bind:value={firstName}

                />
            </div>
            <div class="form__field">
                <label class="form__label">Last Name</label>
                <input
                        class="form__input"
                        id="lastName"
                        name="lastName"
                        type="text"
                        bind:value={lastName}

                />
            </div>
        </div>

        <div class="form__section">
            <div class="form__field--fullWidth">
                <label class="form__label">Email</label>
                <input
                        class="form__input"
                        id="email"
                        name="email"
                        type="email"
                        bind:value={email}

                />
            </div>
        </div>

        <div class="form__section">
            <div class="form__field--fullWidth">
                <label class="form__label">Message</label>
                <textarea
                        class="form__input form__textarea"
                        id="message"
                        name="message"
                        bind:value={message}></textarea>
            </div>
        </div>

        <button class='button button__ghost button--extraPadding' on:click={handleSubmit}>Send</button>
    </form>

</div>

<style lang="scss">
  @import "src/styles/form.scss";
</style>
