// svelte/src/routes/form.svelte
<script>
	// import { browser, dev } from '$app/env';
	//
	// // we don't need any JS on this page, though we'll load
	// // it in dev so that we get hot module replacement...
	// export const hydrate = dev;
	//
	// // ...but if the client-side router is already loaded
	// // (i.e. we came here from elsewhere in the app), use it
	// export const router = browser;
	//
	// // since there's no dynamic data here, we can prerender
	// // it so that it gets served as a static asset in prod
	// export const prerender = true;


	let firstName = '';
	let	lastName = '';
	let email = '';
	let message = '';


</script>

<svelte:head>
	<title>Form</title>
</svelte:head>

<div class="content">

	<pre>First Name: {firstName}</pre>
	<pre>Last Name: {lastName}</pre>
	<pre>Email: {email}</pre>
	<pre>Message: {message}</pre>

	<form class="form">
		<h1>Form</h1>
		<div class="form__section">
			<div class="form__field">
				<label class="form__label">First Name</label>
				<input
						class="form__input"
						id="firstName"
						name="firstName"
						type="text"
						bind:value={firstName}

				/>
			</div>
			<div class="form__field">
				<label class="form__label">Last Name</label>
				<input
						class="form__input"
						id="lastName"
						name="lastName"
						type="text"
						bind:value={lastName}

				/>
			</div>
		</div>

		<div class="form__section">
			<div class="form__field--fullWidth">
				<label class="form__label">Email</label>
				<input
						class="form__input"
						id="email"
						name="email"
						type="email"
						bind:value={email}

				/>
			</div>
		</div>

		<div class="form__section">
			<div class="form__field--fullWidth">
				<label class="form__label">Message</label>
<!--				<textarea-->
<!--						className="form__input form__textarea"-->
<!--						id="message"-->
<!--						name="message"-->
<!--						value={formState.message}></textarea>-->
			</div>
		</div>

		<button
				class='button button__ghost button--extraPadding'
		>
			Send
		</button>
	</form>


</div>

<style>
	.content {
		width: 100%;
		max-width: var(--column-width);
		margin: var(--column-margin-top) auto 0 auto;
	}
</style>

// react/src/components/Form.jsx
import React, {useState} from 'react'
import './form.scss'

export const Form = () => {

  const initState = {
    firstName: '',
    lastName: '',
    email: '',
    message: ''
  }

  const [formState, setFormState] = useState(initState)

  const handleOnChange = (e) => {
    setFormState({...formState, [e.target.name]: e.target.value})
  }

  const handleSubmit = () => {
    alert(`Form submitted!! firstName: ${formState.firstName}, lastName: ${formState.lastName}, email: ${formState.email}, message: ${formState.message}` )
  }

  return (
    <div className="form__wrapper">

      <form className="form">
      <h1>Form</h1>
        <div className="form__section">
          <div className="form__field">
            <label className="form__label">First Name</label>
            <input
              className="form__input"
              id="firstName"
              name="firstName"
              type="text"
              value={formState.firstName}
              onChange={handleOnChange}
            />
          </div>
          <div className="form__field">
            <label className="form__label">Last Name</label>
            <input
              className="form__input"
              id="lastName"
              name="lastName"
              type="text"
              value={formState.lastName}
              onChange={handleOnChange}
            />
          </div>
        </div>

        <div className="form__section">
          <div className="form__field--fullWidth">
            <label className="form__label">Email</label>
            <input
              className="form__input"
              id="email"
              name="email"
              type="email"
              value={formState.email}
              onChange={handleOnChange}
            />
          </div>
        </div>

        <div className="form__section">
          <div className="form__field--fullWidth">
            <label className="form__label">Message</label>
            <textarea
              className="form__input form__textarea"
              id="message"
              name="message"
              value={formState.message}
              onChange={handleOnChange}
            />
          </div>
        </div>


        <button
          className='button button__ghost button--extraPadding'
          onClick={handleSubmit}
        >
          Send
        </button>
      </form>
    </div>
  )
}
